name: BudgetNow
description: Simple Budgeting Tool. Get your spending in order!
full_description: 'BudgetNow is a simple budgeting tool that allows you to manually track income and expenses in custom budgeting categories. You can create as many transactions and budgets as you'd like, but your budgets will only reflect transactions for the current month.<br>
<br>With a lot of features:
<br>- Create unlimited custom budget categories
<br>- Create unlimited transactions, and categorize each to a budget
<br>- Review your current months spending
<br>- And its 100% free!'
iOS: https://telegra.ph/Replace-this-link-07-23
screenshots:
  - 1.png
  - 2.png
  - 3.png
  - 4.png
producthunt: https://telegra.ph/Replace-this-link-07-23
companies:
  - url: https://telegra.ph/Replace-this-link-07-23
    image: androidpolice.png
  - url: https://telegra.ph/Replace-this-link-07-23
    image: producthunt.png
